### ISSUE TITLE
[BUG] Unable to detect asset bundle

### ISSUE THREAD

**Issue by kiraio-moe** [kiraio-moe/Reverse1999-Anarchist#1]
In unusable state right now. Will fix this soon.

**Comment by populated** [comment]
> In unusable state right now. Will fix this soon.

Interesting

**Comment by kiraio-moe** [comment]
> > In unusable state right now. Will fix this soon.
> 
> Interesting

Yeah, I checked it last week and it's not work.
When I commit them it's work(?) Nah, maybe my head doesn't right at the time.

**Comment by populated** [comment]
> > > In unusable state right now. Will fix this soon.
> > 
> > 
> > Interesting
> 
> Yeah, I checked it last week and it's not work. When I commit them it's work(?) Nah, maybe my head doesn't right at the time.

I could possibly take a look at the code and fix it. You seemed to mention our code as inspo (wanderer-moe, I wrote the Golang rewrite of the original reverse1999 repo, and README). Anyway, yeah, I can take a look at it once I'm free and then make a PR. It depends on whether you're planning on fixing it right now. If not, I will do it for you.

**Comment by kiraio-moe** [comment]
> > > > In unusable state right now. Will fix this soon.
> > > 
> > > 
> > > Interesting
> > 
> > 
> > Yeah, I checked it last week and it's not work. When I commit them it's work(?) Nah, maybe my head doesn't right at the time.
> 
> I could possibly take a look at the code and fix it. You seemed to mention our code as inspo (wanderer-moe, I wrote the Golang rewrite of the original reverse1999 repo, and README). Anyway, yeah, I can take a look at it once I'm free and then make a PR. It depends on whether you're planning on fixing it right now. If not, I will do it for you.

I have done fixing the decryption process in my local and on WIP for the encryption.
IDK when it will finish. Just no time/courage to take it.

A PR? That will great :)

**Comment by kiraio-moe** [comment]
Fixed in [10a8953](https://github.com/kiraio-moe/Reverse1999-Anarchist/commit/10a895341a2b7fb5e7edc32449938e9ddab746e9). Sorry, but thanks for caring to fix this @alluding :)

**Comment by populated** [comment]
> Fixed in [10a8953](https://github.com/kiraio-moe/Reverse1999-Anarchist/commit/10a895341a2b7fb5e7edc32449938e9ddab746e9). Sorry, but thanks for caring to fix this @alluding :)

All good :]
